### ISSUE TITLE
self-signing to avoid testsigning mode, can't verify signature?

### ISSUE THREAD

**Issue by samkitty** [forderud/BatterySimulator#17]
Hey, I've been using your project for fun and it's working quite well. Though I would love to be able to use it without having to turn on test signing mode, so I did the following:

`>C:\Program Files (x86)\Windows Kits\10\bin\x86>inf2cat /driver:C:\Users\Duo\Desktop\simbatt\simbatt /os:7_X64,Server2008R2_X64,8_X64,Server8_X64 /v`
`Parsing INF: C:\Users\Duo\Desktop\simbatt\simbatt\simbatt.inf`
`Finished parsing INFs`
`Processing INF: C:\Users\Duo\Desktop\simbatt\simbatt\simbatt.inf`
`Finished processing INFs`
`>C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86>makecert -r -n "CN=selfsigning" -ss self-signed -sr LocalMachine`
`Succeeded`
`>C:\Program Files (x86)\Windows Kits\10\App Certification Kit>signtool sign /s Win-RAIDStore /n "Win-RAID CA" /fd SHA1 /t http://timestamp.comodoca.com/authenticode C:\Users\Duo\Desktop\simbatt\simbatt\simbatt.cat`
`Done Adding Additional Store`
`Successfully signed: C:\Users\Duo\Desktop\simbatt\simbatt\simbatt.cat`

I have also added the certificate to **Trusted Root Certification Authorities** and **Trusted Publishers**.

The installation scripts succeeds and I can see the simulated battery in device manager, however it has the ⚠️ mark and complains that windows was unable to verify the signature. 
![image](https://github.com/forderud/BatterySimulator/assets/57629730/ee5df6bc-cb86-4c17-ae2c-8b848e3142a5)
![image](https://github.com/forderud/BatterySimulator/assets/57629730/6b6e78d6-f531-4abc-9600-e8bcc9ed1bff)
(ignore cert name).

Any idea what I might be missing? or is testsigning mode really the only way for this driver to work?

Thanks!

**Comment by forderud** [comment]
Thank you for taking a liking in this project.

You´ll probably need to  join https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register to get your driver signed by Microsoft if you want to avoid enabling "testsigning".
