### ISSUE TITLE
Windows 10 x86 or Vista x86 support?

### ISSUE THREAD

**Issue by KoleckOLP** [forderud/BatterySimulator#20]
Hello, I would like to ask if it's possible to sumulate a battery on a 32bit Windows 10, or perhaps Vista.
I need to simulate battery on a laptop with that doesn't have one.
All I need is for windows to think there is a battery and that is has a charge.
Thank you, and sorry if this is unrelated to you project.

**Comment by forderud** [comment]
I haven't tested, but the `simbatt` project is most likely also compatible with 32bit Windows back to Windows 10. However, 32bit support was removed in 312d16301ef128947520e99a35b09995d7b21d33 so you'll need to add it back again yourself. Alternatively, you can build the official https://github.com/microsoft/Windows-driver-samples/tree/main/simbatt sample project from Microsoft, where 32bit support is still present.
